### ISSUE TITLE
posenet 관련 Error

### ISSUE THREAD

**Issue by Seunghui98** [Eye-Remocon/Pose_Detection#2]
1. 사전 설치  
- node.js 설치
- npm 패키지 설치 , [관련 npm 패키지 사이트](https://www.npmjs.com/package/@teachablemachine/pose)
```
$ npm i @tensorflow/tfjs
$ npm i @teachablemachine/pose
$ npm i canvas
$ npm i fs
$ npm i http
```
- [참고 GitHub](https://github.com/googlecreativelab/teachablemachine-community/tree/master/libraries/pose). 

2. 이미지 파일 그대로 명시
```
const tf = require('@tensorflow/tfjs');
const fs = require('fs');
const tmPose = require('@teachablemachine/pose');
global.fetch = require("node-fetch");


const URL = "https://teachablemachine.withgoogle.com/models/ZXEZyolyru/";
let model, webcam, ctx, labelContainer, maxPredictions;

async function init() {
    const modelURL = URL + "model.json";
    const metadataURL = URL + "metadata.json";

    model = await tmPose.load(modelURL, metadataURL);

    tmPose.load(modelURL, metadataURL).then(mod => {
        model = mod;
        maxPredictions = model.getTotalClasses();

    }).catch(err => console.log(err));

}

async function predict() {
  
    const { pose, posenetOutput } = await model.estimatePose("clap.jpg", false);
    console.log(posenetOutput)
    const prediction = await model.predict(posenetOutput);



    for (let i = 0; i < maxPredictions; i++) {
        const classPrediction =
            prediction[i].className;
        labelContainer.childNodes[i].innerHTML = classPrediction;
    }
    console.log(classPrediction);
    return classPrediction;
}
async function main() {
    await init();
    //upload();
    await predict();
}

main();
```
- const { pose, posenetOutput } = await model.estimatePose("clap.jpg", false);
이 부분에서 이미지 파일 그대로 명시하면 다음과 같은 에러 발생  
- <img width="1737" alt="스크린샷 2021-08-15 오후 11 34 38" src="https://user-images.githubusercontent.com/54658745/129482100-8f66db7f-aae0-49bc-84f4-6aff92a3c272.png">

- 하지만 해당 방법으로 pose 이용하는 [Github](https://github.com/michael-fourie/DanceParty/blob/main/backend/model/tensorflow.js)

3. html에서 사용되는 canvas로 웹브라우저에 이미지 띄운 후 해당 canvas로 예측하는 경우  
```
const http = require('http');
const fs = require('fs');
const Canvas = require('canvas');
const tmPose = require('@teachablemachine/pose');
global.fetch = require("node-fetch");


const URL = "https://teachablemachine.withgoogle.com/models/ZXEZyolyru/";
let model, webcam, ctx, labelContainer, maxPredictions;

async function init() {
    const modelURL = URL + "model.json";
    const metadataURL = URL + "metadata.json";

    model = await tmPose.load(modelURL, metadataURL);

    tmPose.load(modelURL, metadataURL).then(mod => {
        model = mod;
        maxPredictions = model.getTotalClasses();

    }).catch(err => console.log(err));

}

async function predict() {
    let canvas;
    http.createServer(function (req, res) {
        fs.readFile(__dirname + '/clap.jpg', async function(err, data) {
            if (err) throw err;
            const img = await Canvas.loadImage(data);
            canvas = new Canvas.Canvas(img.width, img.height);
            const ctx = canvas.getContext('2d');
            ctx.drawImage(img, 0, 0, img.width, img.height);

            res.write('<html><body>');
            res.write('<img src="' + canvas.toDataURL() + '" />');
            res.write('</body></html>');

            const { pose, posenetOutput } = await model.estimatePose(canvas, false);
            console.log(posenetOutput)
            const prediction = await model.predict(posenetOutput);


            res.end();
        });

    }).listen(8124, "127.0.0.1");
    console.log('Server running at http://127.0.0.1:8124/');

}

async function main() {
    await init();
    await predict();
}

main();
```
- 
<img width="1746" alt="스크린샷 2021-08-15 오후 11 42 50" src="https://user-images.githubusercontent.com/54658745/129482317-6140e0d6-2e2d-4321-9d36-3a98e1536ccd.png">
- TypeError: forwardFunc is not a function라는 에러 발생해서 찾아보니깐 @tensorflow/tfjs 패키지의 버전 문제라고 합니다.
그래서 패키지버전 최신으로 업데이트 하였지만 에러가 해결되지 않았습니다.

그 외에 이미지를 웹브라우저에 띄우지 않고 node.js 내에서 canvas안에 이미지 넣어서 canvas로 예측해보려고 했으나
3번과 같은 똑같은 에러가 발생하였습니다.

해당 이슈를 해결할 수 있는 조언 부탁드립니다 !!!!!

@t25kim @lspc678 @Ryumaker @woniiiii

**Comment by smarthome-hanium** [comment]
첫번째 그림에 Error: pixels passed to tf.browser.fromPixels() must be either an HTMLVideoElement, HTMLImageElement, HTMLCanvasElement, ImageData in browser, or OffscreenCanvas, ImageData in webworker or {data: Uint32Array, width: number, height: number}, but was String 라는 오류 메시지가 있어서 webworker 활용하여 ImageData로 바꾸니 그 부분은 넘어가는데 다른 오류가 나네요. 
expected dense_Dense3_input to have shape [null,14739] but got array with shape [1,1].

```
ImageData {
  data: Uint8ClampedArray(12096000) [
    179, 108, 28, 255, 178, 107, 27, 255, 177, 106, 26, 255,
    175, 104, 24, 255, 173, 103, 21, 255, 172, 102, 20, 255,
    170, 100, 16, 255, 170, 100, 16, 255, 167,  97, 11, 255,
    167,  97, 11, 255, 167,  98,  9, 255, 166,  97,  8, 255,
    166,  97,  6, 255, 165,  96,  5, 255, 165,  96,  5, 255,
    165,  96,  5, 255, 170,  98,  0, 255, 170,  98,  0, 255,
    169,  99,  0, 255, 170, 100,  1, 255, 170, 100,  1, 255,
    171, 101,  2, 255, 169, 101,  4, 255, 169, 101,  4, 255,
    169, 100,  9, 255,
    ... 12095900 more items
  ],
  width: 2400,
  height: 1260
}
(node:5314) UnhandledPromiseRejectionWarning: Error: Error when checking : expected dense_Dense3_input to have shape [null,14739] but got array with shape [1,1].
    at new ValueError (/home/t25kim/pose/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:189:28)
    at checkInputData (/home/t25kim/pose/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:8794:31)
    at LayersModel.predict (/home/t25kim/pose/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:9422:9)
    at Sequential.predict (/home/t25kim/pose/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:10879:27)
    at CustomPoseNet.<anonymous> (/home/t25kim/pose/node_modules/@teachablemachine/pose/dist/custom-posenet.js:284:45)
    at step (/home/t25kim/pose/node_modules/@teachablemachine/pose/dist/custom-posenet.js:33:23)
    at Object.next (/home/t25kim/pose/node_modules/@teachablemachine/pose/dist/custom-posenet.js:14:53)
    at /home/t25kim/pose/node_modules/@teachablemachine/pose/dist/custom-posenet.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/t25kim/pose/node_modules/@teachablemachine/pose/dist/custom-posenet.js:4:12)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by Seunghui98** [comment]
@smarthome-hanium 해결법 감사합니다 !! webworker 방식으로 해보려고 하는데, 혹시
[패키지 사이트](https://www.npmjs.com/package/jpeg-web-worker) 이 패키지를 사용하셔서 ImageData를 만드셨을까요 ??
그리고 혹시 webwoker로 ImageData 생성할 때 Canvas를 사용하나요 ... ?

**Comment by Seunghui98** [comment]
@smarthome-hanium 
멘토님 !!!!!!!!! 덕분에 이슈 해결하였습니다 !!! 감사합니다 :) 
![K-033](https://user-images.githubusercontent.com/54658745/129572768-be652314-a82f-477d-8127-9b46ccc16907.png)

@teachablemachine/pose의 패키지가 @tensorflow/tfjs@1.3.1 버전과 의존관계가 있어서 자꾸 오류가 난 것 같습니다.

저는 Canvas 이용해서 prediction값 얻었는데 혹시, webworker로 처리하면 좀 더 간결하고 빨리 처리할 수 있을까요 ?

**Comment by smarthome-hanium** [comment]
잘 하셨어요~ 저는 @tensorflow/tfjs@1.3.1 로 처음부터 설치하고는 했는데... 정상 결과까지는 안되었네요 ㅎㅎ
도움이 되실까해서 제가 테스트했던 코드 올려드리니까 한번 봐주세요. 
https://github.com/Eye-Remocon/Pose_Detection/tree/sample/sample
